import 'dart:core';


final List<String> movieGenres = ['Drama', 'Comedy', 'Horror', 'Action', 'Anime'];

// drama movies (image path, movie title, director/year)
final List<String> dontWorryDarling = ["images/dontworrydarling.jpg", "Don't Worry Darling", "Olivia Wilde, 2022", "https://www.imdb.com/title/tt10731256/", "2h 3m", "Florence Pugh, Harry Styles, Chris Pine", "https://en.wikipedia.org/wiki/Don't_Worry_Darling", "“Don’t Worry Darling” (2022) tells an intricate and visually captivating story about marriage dynamics from a perspective not often considered. 3.4/5 -Rosa Parra\n\nThematically it's all over the place, never quite figuring out how to synthesize its ideas in a coherent or satisfying way. 2.5/4 -Mattie Lucas"];
final List<String> gladiator = ["images/gladiator.jpg", "Gladiator", "Ridley Scott, 2000", "https://www.imdb.com/title/tt0172495/?ref_=fn_al_tt_1", "2h 35m", "Russell Crowe, Joaquin Phoenix, Connie Nielsen", "https://en.wikipedia.org/wiki/Gladiator_(2000_film)", 'Gladiator delivers everything its title promises. The surprise is that this bold revival of the period "sword-and-sandals" epic does so with solid acting, sure pacing and superior style interspersed with payoff-worthy pathos. 4/5 -Dean Lamanna\n\nA mountain, a fever dream, an epic poem of a motion picture. Equal parts Ben-Hur and Braveheart, it is a victory not likely to be equaled any time soon. 4/4 -Rick Kisonak'];
final List<String> schindlersList = ["images/schindler.jpg", "Schindler's List", "Steven Spielberg, 1993", "https://www.imdb.com/title/tt0108052/?ref_=nv_sr_srsg_0", "3h 15m", "Liam Neeson, Ralph Fiennes, Ben Kingsley", "https://en.wikipedia.org/wiki/Schindler%27s_List", 'A film of immense power and the deepest sincerity. 5/5 -Keith Garlington\n\nFew films have ever dealt so chillingly with what philosopher Hannah Arendt called "the banality of evil." 3.5/4 -Lawrence Toppman'];
final List<String> ladyBird = ["images/ladybird.jpg", "Lady Bird", "Greta Gerwig, 2017", "https://www.imdb.com/title/tt4925292/?ref_=nv_sr_srsg_0", "1h 34m", "Saoirse Ronan, Laurie Metcalf, Tracy Letts", "https://en.wikipedia.org/wiki/Lady_Bird_(film)", "Its 2002 post-911 setting feels relevant, its portrait of adolescence feels genuine and personal, and its pitch-perfect and bittersweet final shot lands just right. 4/5 -Keith Garlington\n\nSaoirse Ronan's stunning portrayal of adolescence is completely lacking in vanity. 5/5 -Yasmin Omar"];
final List<String> zodiac = ["images/zodiac.jpg", "Zodiac", "David Fincher, 2007", "https://www.imdb.com/title/tt0443706/?ref_=nv_sr_srsg_0", "2h 37m", "Jake Gyllenhaal, Robert Downey Jr., Mark Ruffalo", "https://en.wikipedia.org/wiki/Zodiac_(film)", "Downey Jr is perfect as the alcoholic wastrel of a crime reporter Paul Averi, as is Mark Raffalo as the dependable cop David. 3/4 -Namrata Joshi\n\nFincher's most mature work to date will earn respect over time. 4/5 -Wendy Ide"];

// comedy movies (image path, movie title, director/year)
final List<String> hotFuzz = ["images/hotfuzz.jpg", "Hot Fuzz", "Edgar Wright, 2007", "https://www.imdb.com/title/tt0425112/?ref_=nv_sr_srsg_0", "2h 1m", "Simon Pegg, Nick Frost, Martin Freeman", "https://en.wikipedia.org/wiki/Hot_Fuzz", "Becomes quite a funny, surreally silly affair after a very slow start. 3/5 -Leigh Paatsch\n\nWright understands how to perfectly balance action, comedy, drama, and suspense, and it pays off. -Jade Budowski"];
final List<String> theMask = ["images/themask.jpg", "The Mask", "Chuck Russell, 1994", "https://www.imdb.com/title/tt0110475/?ref_=nv_sr_srsg_0", "1h 41m", "Jim Carrey, Cameron Diaz, Peter Riegert", "https://en.wikipedia.org/wiki/The_Mask_(1994_film)", "Carrey may be the finest comic to come along since Robin Williams. 3/4 -Stephen Wigler\n\nIf a movie star was born in Ace Ventura, he is christened in The Mask. Quite simply, this is the best and freest crazy comedy to come along since Beetlejuice. -Jay Boyar"];
final List<String> schoolOfRock = ["images/schoolofrock.jpg", "School of Rock", "Richard Linklater, 2003", "https://www.imdb.com/title/tt0332379/?ref_=nv_sr_srsg_0", "1h 49m", "Jack Black, Mike White, Joan Cusack", "https://en.wikipedia.org/wiki/School_of_Rock", "Powered almost entirely by Black's infectious charisma and eccentricity, School of Rock is raucous and heartwarming comedy. -Toussaint Egan\n\nIt's genuinely good hearted, and features child actors that look like real kids, all permeation of geeky, fat, skinny, sullen and silent in that way that only actual kids can be. -Dorothy Woodend"];
final List<String> mrsDoubtfire = ["images/mrsdoubtfire.jpg", "Mrs. Doubtfire", "Chris Columbus, 1993", "https://www.imdb.com/title/tt0107614/?ref_=nv_sr_srsg_0", "2h 5m", "Robin Williams, Sally Field, Pierce Brosnan", "https://en.wikipedia.org/wiki/School_of_Rock", "A somewhat grotesque take on Mary Poppins, this picture has an attitude and style all its own. -Mike Massie\n\nThis comedy's warm and soothing nature will give mainstream audiences in these dysfunctional-family times a perfect holiday uplift. -Duane Byrge"];
final List<String> napoleonDynamite = ["images/napoleon.jpg", "Napoleon Dynamite", "Jared Hess, 2004", "https://www.imdb.com/title/tt0374900/?ref_=nv_sr_srsg_0", "1h 36m", "Jon Heder, Efren Ramirez, Jon Gries", "https://en.wikipedia.org/wiki/Napoleon_Dynamite", "It actually lived up to the hype. -Rachel Wagner\n\nOne-of-a-kind high school comedy for the family. 4/5 -Nell Minow"];

// horror movies (image path, movie title, director/year)
final List<String> it = ["images/it.jpeg", "It", "Andy Muschietti, 2017", "https://www.imdb.com/title/tt1396484/?ref_=nv_sr_srsg_3", "2h 15m", "Bill Skarsgård, Jaeden Martell, Finn Wolfhard", "https://en.wikipedia.org/wiki/It_(2017_film)", "It like Pennywise is a being of its own - a blend of The Goonies and A Nightmare on Elm Street. 4/4 -David Gonzalez\n\nA freaky reboot with creepy moments. 4/5 -Dan Stubbs"];
final List<String> candyman = ["images/candyman.jpg", "Candyman", "Bernard Rose, 1992", "https://www.imdb.com/title/tt0103919/?ref_=nv_sr_srsg_3", "1h 39m", "Virginia Madsen, Xander Berkeley, Tony Todd", "https://en.wikipedia.org/wiki/Candyman_(1992_film)", "Still something of a classic, thanks largely to Tony Todd’s grand performance in the title role, literally a tortured artist out for vengeance. -Randall King\n\nTony Todd shot to international stardom in this Chicago-based horror hit... -Dann Gire"];
final List<String> scream = ["images/scream.jpg", "Scream", "Wes Craven, 1996", "https://www.imdb.com/title/tt0117571/?ref_=nv_sr_srsg_0", "1h 51m", "Neve Campbell, Courteney Cox, David Arquette", "https://en.wikipedia.org/wiki/Scream_(1996_film)", "Through reinvention and self-awareness, Scream brought the slasher genre to new, fun, and bloody heights. -Kristy Strouse\n\nA masterclass in horror cinema. Funny, scary, entertaining. You can't go wrong with Scream. 5/5 -Trace Thurman"];
final List<String> aQuietPlace = ["images/aquietplace.jpg", "A Quiet Place", "John Krasinski, 2018", "https://www.imdb.com/title/tt6644200/?ref_=nv_sr_srsg_0", "1h 30m", "Emily Blunt, John Krasinski, Millicent Simmonds", "https://en.wikipedia.org/wiki/A_Quiet_Place", "I did find it compelling-as long as I didn't think about what was happening. -FLetcher Powell\n\nThe tension in the film was amazing. 8/10 -Emma Wolfe"];
final List<String> getOut = ["images/getout.jpg", "Get Out", "Jordan Peele, 2017", "https://www.imdb.com/title/tt5052448/?ref_=nv_sr_srsg_0", "1h 44m", "Daniel Kaluuya, Allison Williams, Bradley Whitford", "https://en.wikipedia.org/wiki/Get_Out", "Get Out is horror filmmaking at its absolute finest. 5/5 -Drew Dietsch\n\nIts sucker punch to the status quo has ensured it's impossible to forget. 5/5 -Yasmin Omar"];

// action movies (image path, movie title, director/year)
final List<String> terminator = ["images/terminator.jpg", "The Terminator", "James Cameron, 1984", "https://www.imdb.com/title/tt0088247/?ref_=nv_sr_srsg_0", "1h 47m", "Arnold Schwarzenegger, Linda Hamilton, Michael Biehn", "https://en.wikipedia.org/wiki/The_Terminator", "It's a powerhouse sci-fi action adventure which is undeniably the most thrill-packed movie- going experience for ages -Alan Jones\n\nAlthough not a horror movie in the strictest sense, the film also introduced us to one of cinema's most iconic final girls... -Howard Gorman"];
final List<String> predator = ["images/predator.jpg", "Predator", "John McTiernan, 1987", "https://www.imdb.com/title/tt0093773/?ref_=nv_sr_srsg_0", "1h 47m", "Arnold Schwarzenegger, Carl Weathers, Kevin Peter Hall", "https://en.wikipedia.org/wiki/Predator_(film)", "Although it could stand to lose a few pounds from its mid-section, Predator benefits greatly from a strong cast and an exceptional monster. -Dan Geringer\n\nEpisode 8: Sex, Lies and Predator -Taylor Baker"];
final List<String> roboCop = ["images/robocop.jpg", "RoboCop", "Paul Verhoeven, 1987", "https://www.imdb.com/title/tt0093870/?ref_=nv_sr_srsg_0", "1h 42m", "Peter Weller, Nancy Allen, Dan O'Herlihy", "https://en.wikipedia.org/wiki/RoboCop", "Aside from some period-specific filmmaking choices, the film hasn’t aged a day. (35th anniversary) -Stephen Silver\n\n35 years after its initial release, RoboCop remains as biting a political satire as ever ... -Douglas Davidson"];
final List<String> matrix = ["images/matrix.jpg", "The Matrix", "The Wachowskis, 1999", "https://www.imdb.com/title/tt0133093/?ref_=nv_sr_srsg_0", "2h 16m", "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss", "https://en.wikipedia.org/wiki/The_Matrix", "A cinematic landscape without The Matrix would be as barren as the scorched earth above Zion. -Danilo Castro\n\nKeanu Reeves and Carrie-Anne Moss are brilliant in their iconic roles. -George Fenwick"];
final List<String> heat = ["images/heat.jpg", "Heat", "Michael Mann, 1995", "https://www.imdb.com/title/tt0113277/?ref_=nv_sr_srsg_0", "2h 50m", "Al Pacino, Robert De Niro, Val Kilmer", "https://en.wikipedia.org/wiki/Heat_(1995_film)", "The movie is lacking in both heart and soul, but it makes up for it with sheer voyeurism. -Mal Vincent\n\nTwenty-six years after it was released, I'm not sure that Heat has ever been bettered as an action film, or as a crime drama. -Graeme Tuckett"];

// anime movies (image path, movie title, director/year)
final List<String> dbzBroly = ["images/dbzbroly.jpeg", "Dragon Ball Super: Broly", "Tatsuya Nagamine, 2018", "https://www.imdb.com/title/tt7961060/?ref_=nv_sr_srsg_0", "1h 40m", "Masako Nozawa(voice), Aya Hisakawa(voice), Ryô Horikawa(voice)", "https://en.wikipedia.org/wiki/Dragon_Ball_Super:_Broly", "I never expected to walk out of a Dragon Ball movie with an emotional connection to a Saiyan fighter, but DBS: Broly truly punches in a whole new way. -Will Harrison\n\nIn the end Dragon Ball Super: Broly gave me something of a tiny headache. 2.5/4 -Sara Michelle Fetters"];
final List<String> ponyo = ["images/ponyo.jpg", "Ponyo", "Hayao Miyazaki, 2008", "https://www.imdb.com/title/tt0876563/?ref_=nv_sr_srsg_0", "1h 41m", "Cate Blanchett(English version), Matt Damon(English version), Liam Neeson(English version)", "https://en.wikipedia.org/wiki/Ponyo", "Fun but more for the kiddies. -Matt Brunson\n\nPonyo gets it. There are other, different worlds than this, but they don't have what we have. -Gena Radcliffe"];
final List<String> aSilentVoice = ["images/silentvoice.jpg", "A Silent Voice", "Naoko Yamada, 2016", "https://www.imdb.com/title/tt5323662/?ref_=nv_sr_srsg_0", "2h 10m", "Miyu Irino(voice), Saori Hayami(voice), Aoi Yûki(voice)", "https://en.wikipedia.org/wiki/A_Silent_Voice_(film)", "A marvelously subtle work of visual storytelling. -Tim Brayton\n\nI think the key to this film ... is self-loathing in its various forms. -CJ Sheu"];
final List<String> yourName = ["images/yourname.jpeg", "Your Name", "Makoto Shinkai, 2016", "https://www.imdb.com/title/tt5311514/?ref_=nv_sr_srsg_0", "1h 46m", "Ryûnosuke Kamiki(voice), Mone Kamishiraishi(voice), Ryô Narita(voice)", "https://en.wikipedia.org/wiki/Your_Name", "Japanese animated fantasy; humorous, romantic, captivating and utterly beautiful. -Alix Turner\n\nSo come for the first act, stay for the dynamic camera. -CJ Sheu"];
final List<String> spiritedAway = ["images/spiritedaway.jpg", "Spirited Away", "Hayao Miyazaki, 2001", "https://www.imdb.com/title/tt0245429/?ref_=nv_sr_srsg_0", "2h 5m", "Daveigh Chase(English version), Suzanne Pleshette(English version), Miyu Irino(voice)", "https://en.wikipedia.org/wiki/Spirited_Away", "An audacious viewing experience. 5/5 -Kevin Maher\n\nSpirited Away is the great treasure of 21st-century animation, and we may still be saying that when the 21st century ends. -Nigel Andrews"];

//list of movies in each genre
final List<List> dramaMovies = [dontWorryDarling, gladiator, schindlersList, ladyBird, zodiac];
final List<List> comedyMovies = [hotFuzz, theMask, schoolOfRock, mrsDoubtfire, napoleonDynamite];
final List<List> horrorMovies = [it,candyman,scream,aQuietPlace,getOut];
final List<List> actionMovies = [terminator,predator,roboCop,matrix,heat];
final List<List> animeMovies = [dbzBroly, ponyo, aSilentVoice, yourName, spiritedAway];

//list of all movies from all genres
final List<List> listOfMovies = [dramaMovies,comedyMovies,horrorMovies,actionMovies,animeMovies];

class PassInfo {
  final String movieName;
  final String imagePath;
  final String director;
  final String imdb;
  final String movieStars;
  final String movieRatings;
  final String movieRuntime;

  const PassInfo(this.movieName, this.imagePath, this.director, this.imdb, this.movieStars, this.movieRatings, this.movieRuntime);
}